---
resources:
  - name: concourse-examples
    type: git
    icon: github
    source:
      uri: https://github.com/ssun3/selfupdate

jobs:
  # update this pipeline before updating child pipelines
  - name: set-self
    public: true
    plan:
      - get: concourse-examples
        trigger: true
      - set_pipeline: ssun3-self-updating-pipeline
        file: concourse-examples/pipelines/set-pipelines.yml
  - name: set-example-pipelines
    public: true
    plan:
      - get: concourse-examples
        trigger: true
        passed: [set-self]
      - set_pipeline: ssun3-git-trigger
        file: concourse-examples/pipelines/git-triggered.yml
